#!/usr/bin/env bash
#transfer file 'file' to a server
#scp / path/to/file username@a:/path/to/destination
#handcoded: scp -i ~/.ssh/id_rsa README.md ubuntu@35.229.61.60

#if number of arguments is >= 3
if [ $# -lt 4]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi