#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

apt-get update
apt-get install -y nginx
sed -i '11i\add_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf
service nginx restart